### ISSUE TITLE
Directory not built when it does not exist on Windows

### ISSUE THREAD

**Issue by jknowles** [wbuchanan/eda#18]
Running this example:

```
sysuse auto
 eda, r(`"`c(pwd)'/edaexamples"') o("minexample")
```

Results in the following error:

```
directory C:/Stata/edaexamples not found
```

On Windows. 

After creating the directory manually and running EDA once, the directory fails to be deleted and rebuilt automatically, instead this code:

```
 eda, r(`"`c(pwd)'/edaexamples"') o("minexample")
```

gives this error:

```
.  eda, r(`"`c(pwd)'/edaexamples"') o("minexample")
Directory exists and rebuild option not specified.  No further action
Directory exists and rebuild option not specified.  No further action
file handle doc already exists
r(110);
```

I'm running Stata/SE 14.2 on Windows 10 with administrative privileges.

**Comment by wbuchanan** [comment]
@jknowles 
I thought I had fixed that at some point.  It might be that I didn't push those changes into the gh-pages branch yet.  I may not be able to get to it this week, but there is a short fix in `eda.ado` where you'd need to add the rebuild option to the `dirfile` command.  I'll try to see if I've already fixed it locally and if I have I'll push the changes.

**Comment by wbuchanan** [comment]
@jknowles 
It is definitely an issue with `dirfile.ado` (at least in part).  The version of `dirfile` that should be included here is located at https://github.com/wbuchanan/dirfile/blob/master/dirfile.ado.  The version in master and on the gh-pages branch may not include some of the modifications to `eda` either, but that should be easy to spot.  

There is a separate bug that I’ve noticed since using Stata 16 that is preventing the scatterplot smoothers from being displayed properly that I need to look into, but I should be able to push an updated version this morning (assuming I don’t run into any issues with Jekyll along the way).

**Comment by wbuchanan** [comment]
@jknowles 
You should be able to use `ado update, update` to get the more recently updated version of eda.  There is now a `rebuild` option available for the `eda` command that should deal with the issue you ran into.  If the directory already exists and contains a bunch of the output, it is much easier to delete the contents of the directory and then call eda.

**Comment by jknowles** [comment]
I think you fixed the original issue, but now when rebuilding there is a prompt for `y/n` for removing each individual graph in the `/graphs` subdirectory, which for large reports is quite inconvenient. I will open a new issue/feature request.

**Comment by wbuchanan** [comment]
@jknowles 
That is still a bit of a pain and I'll try to add something to handle those cases sooner than later (e.g., `y/n/all` type option set).
